---
- name: deploy website
  hosts: web
  become: yes
  tasks:

    - name: copy website file
      copy:
        src: "./"
        dest: "/var/www/html"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: ensure that apache2
      service:
        name: apache2
        state: started
        enabled: yes
        